version: '3.2'

networks:
    consul:
      driver: bridge


services:

    traefik:
        image: traefik
        restart: always
        container_name: traefik
        command:
            - "--log.level=INFO"
            - "--api.dashboard=true"
            - "--accesslog=false"
            - "--providers.consulcatalog=true"
            - "--providers.consulcatalog.exposedbydefault=false"
            - "--providers.consulcatalog.endpoint.address=consul-server:8500"
            - "--providers.consulcatalog.endpoint.datacenter=local"
            - "--providers.consulcatalog.prefix=traefik"
            - "--entrypoints.web.address=:80"
        ports:
            - 80:80
        networks:
            - consul
        stdin_open: true
        tty: true
        privileged: true

    consul-server:
        image: hashicorp/consul:1.9.5
        container_name: consul-server
        hostname: consul-server
        volumes: 
            - ./Consul/Server/config/server.json:/consul/config/server.json:rw
        networks:
            - consul
        restart: always
        command: 'agent --bootstrap-expect=1 -config-file=/consul/config/server.json'

                                                                                                                      
    httpd:
        build: 
            context: ./Consul/Agents/httpd
        container_name: httpd
        hostname: httpd
        networks:
            - consul
        restart: always
    
    nginx:
        build: 
            context: ./Consul/Agents/nginx
        container_name: nginx
        hostname: nginx
        networks:
            - consul
        restart: always